# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Juicefs < Formula
  desc "JuiceFS is a distributed POSIX file system built on top of Redis and S3"
  homepage "https://github.com/juicedata/juicefs"
  version "1.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/juicedata/juicefs/releases/download/v1.2.2/juicefs-1.2.2-darwin-amd64.tar.gz"
      sha256 "bca2df7282d4ef945185bb4dd9ed7dbc109cc5a4a33d03bedd15a78ef108de0c"

      def install
        bin.install "juicefs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/juicedata/juicefs/releases/download/v1.2.2/juicefs-1.2.2-darwin-arm64.tar.gz"
      sha256 "67c77066dbb532f7f2b151f4e4bac8a565408224ebb51eb723d66c6101dc6a9c"

      def install
        bin.install "juicefs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/juicedata/juicefs/releases/download/v1.2.2/juicefs-1.2.2-linux-arm64.tar.gz"
      sha256 "f0488040a8a1d26fd95f71b74f8ab2d6215e5773f0a7d63675bfed5dea46274b"

      def install
        bin.install "juicefs"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/juicedata/juicefs/releases/download/v1.2.2/juicefs-1.2.2-linux-amd64.tar.gz"
      sha256 "6b3503971d65f487920658bed0e098be9223e62d26e643b09a793039ab83be17"

      def install
        bin.install "juicefs"
      end
    end
  end
end
