# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Juicesync < Formula
  desc "A tool to move your data between any clouds or regions."
  homepage "https://juicefs.com/"
  version "0.8.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/juicedata/juicesync/releases/download/v0.8.4/juicesync_0.8.4_Darwin_arm64.tar.gz"
      sha256 "b754fc00dd7833ed93a663d17905ffb4e522de86594660d25aed160dcce0051e"

      def install
        bin.install "juicesync"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/juicedata/juicesync/releases/download/v0.8.4/juicesync_0.8.4_Darwin_x86_64.tar.gz"
      sha256 "3653cb5173ee9635b599f39fdd264a1bf674c9c2d159e6b3cd6e90419450b6b8"

      def install
        bin.install "juicesync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/juicedata/juicesync/releases/download/v0.8.4/juicesync_0.8.4_Linux_x86_64.tar.gz"
      sha256 "025deb0fd82d09f620388643f193908806f38305fbb7a9e13fbb68115db72fe2"

      def install
        bin.install "juicesync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/juicedata/juicesync/releases/download/v0.8.4/juicesync_0.8.4_Linux_arm64.tar.gz"
      sha256 "6272f6157f2f53367e6466d79f9259ea24a448619e3e294f0adb89e9ce48f049"

      def install
        bin.install "juicesync"
      end
    end
  end
end
