# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Juicefs < Formula
  desc "JuiceFS is a distributed POSIX file system built on top of Redis and S3"
  homepage "https://github.com/juicedata/juicefs"
  version "1.0.0-alpha4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/juicedata/juicefs/releases/download/v1.0.0-alpha4/juicefs-1.0.0-alpha4-darwin-arm64.tar.gz"
      sha256 "2ab33a131c20d32a49252d86607656efaa74d97150b7ad8086217ebc7090c72f"

      def install
        bin.install "juicefs"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/juicedata/juicefs/releases/download/v1.0.0-alpha4/juicefs-1.0.0-alpha4-darwin-amd64.tar.gz"
      sha256 "7035c68c0bf04a0a98e76c7dcf44b7c55a73fa01e4b90898ca8e551895db5fa7"

      def install
        bin.install "juicefs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/juicedata/juicefs/releases/download/v1.0.0-alpha4/juicefs-1.0.0-alpha4-linux-arm64.tar.gz"
      sha256 "49f54b0c6ee8ca02b9a0752262f610c0654c065cbb1fd8cd3033a37e40bf9ccb"

      def install
        bin.install "juicefs"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/juicedata/juicefs/releases/download/v1.0.0-alpha4/juicefs-1.0.0-alpha4-linux-amd64.tar.gz"
      sha256 "a8e431035e8ddb802971bc5db3fe955156806508847e82161cdd1987c6b47a79"

      def install
        bin.install "juicefs"
      end
    end
  end
end
