# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Juicesync < Formula
  desc "A tool to move your data between any clouds or regions."
  homepage "https://juicefs.com/"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/juicedata/juicesync/releases/download/v1.0.3/juicesync_1.0.3_Darwin_x86_64.tar.gz"
      sha256 "96f1f7c71ba81b178bf3f1f9ff7c46e2b462578e0d62fac7a08301772960cc41"

      def install
        bin.install "juicesync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/juicedata/juicesync/releases/download/v1.0.3/juicesync_1.0.3_Darwin_arm64.tar.gz"
      sha256 "2c4583df9b866e4512c809ca6c47a521566b2563280dfc464f92a834c63a212d"

      def install
        bin.install "juicesync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/juicedata/juicesync/releases/download/v1.0.3/juicesync_1.0.3_Linux_arm64.tar.gz"
      sha256 "c62299d8b7c642b38272e263a766ae0331433c7be87a4b3ac1a6b24010fbf185"

      def install
        bin.install "juicesync"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/juicedata/juicesync/releases/download/v1.0.3/juicesync_1.0.3_Linux_x86_64.tar.gz"
      sha256 "c7fa9511d3506ea38ab9282e99c1b54a251eb5f58b3a1a43d50fef79ec04468f"

      def install
        bin.install "juicesync"
      end
    end
  end
end
